# Generated by Django 5.0.3 on 2024-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('operator_seluler', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pembelian', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('tanggal_transaksi', models.DateField()),
                ('pembeli', models.CharField(max_length=255)),
            ],
        ),
    ]
